"""Flags page — model legislation + conflict detection."""

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

import json
import streamlit as st
import pandas as pd
from components.sidebar import render_sidebar
from components.theme import t, src, footer, page_head
from ingestion.db import get_connection, get_cursor

st.set_page_config(page_title="Flags — {L.A}TTICE", layout="wide")
render_sidebar()

st.markdown(page_head("Flags", "Model legislation patterns and donor–legislation alignment"), unsafe_allow_html=True)


@st.cache_data(ttl=300)
def flag_data():
    conn = get_connection(); cur = get_cursor(conn)
    cur.execute("""SELECT mm.*, b.bill_number, b.title, ba.plain_english, ba.policy_area
        FROM model_matches mm JOIN bills b ON b.id = mm.bill_id
        LEFT JOIN bill_analyses ba ON ba.bill_id = b.id ORDER BY mm.similarity_score DESC""")
    model = [dict(r) for r in cur.fetchall()]
    cur.execute("""SELECT cf.*, l.name as leg_name, l.party, b.bill_number, ba.plain_english, ba.policy_area
        FROM conflict_flags cf JOIN legislators l ON l.id = cf.legislator_id
        JOIN bills b ON b.id = cf.bill_id LEFT JOIN bill_analyses ba ON ba.bill_id = b.id
        ORDER BY CASE cf.severity WHEN 'high' THEN 1 WHEN 'medium' THEN 2 ELSE 3 END""")
    conflicts = [dict(r) for r in cur.fetchall()]
    conn.close()
    return model, conflicts


model, conflicts = flag_data()

tab1, tab2 = st.tabs([f"Model Legislation ({len(model)})", f"Conflict Flags ({len(conflicts)})"])

with tab1:
    if not model:
        st.markdown("""<div class="lc" style="text-align:center;padding:2.5rem;">
            <p style="font-family:'Source Serif 4',serif;font-size:1.1rem;font-weight:600;color:#1c1917;">No model legislation matches detected</p>
            <p style="color:#78716c;font-size:0.82rem;">Bills are screened against known ALEC and SPN template language.</p>
        </div>""", unsafe_allow_html=True)
    else:
        st.markdown(f'<p style="color:#b5b0ab;font-size:0.7rem;margin-bottom:0.5rem;">{len(model)} matches across {len(set(m["bill_id"] for m in model))} bills · {src("keyword pattern matching")}</p>', unsafe_allow_html=True)

        for mm in model:
            score = mm["similarity_score"]
            policy = (mm.get("policy_area") or "").replace("_"," ")
            st.markdown(f"""<div class="lc">
                <div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:0.3rem;">
                    <div style="display:flex;align-items:baseline;gap:0.4rem;">
                        <span style="font-family:'Source Serif 4',serif;font-weight:600;color:#1c1917;">{mm['bill_number']}</span>
                        <span style="font-size:0.63rem;color:#a8a29e;">{policy}</span>
                    </div>
                    <div>{t(mm['matched_source'], 'o')} {t(f"{score:.0%}", 'm')}</div>
                </div>
                <p style="font-size:0.82rem;color:#57534e;line-height:1.6;margin:0 0 0.3rem 0;">{mm.get('matching_sections','')}</p>
                {'<p style="font-size:0.82rem;color:#44403c;line-height:1.6;margin:0;padding:0.6rem 0.8rem;background:#fafaf9;border-radius:6px;border:1px solid #ebe9e7;">'+mm['plain_english'][:200]+'…</p>' if mm.get('plain_english') and len(mm.get('plain_english',''))>0 else ''}
            </div>""", unsafe_allow_html=True)

        # Export
        df = pd.DataFrame([{"bill": m["bill_number"], "source": m["matched_source"],
            "match": m.get("matching_sections",""), "score": m["similarity_score"]} for m in model])
        st.download_button("Export CSV", df.to_csv(index=False), "lattice_model_matches.csv", "text/csv")

with tab2:
    if not conflicts:
        st.markdown("""<div class="lc" style="text-align:center;padding:2.5rem;">
            <p style="font-family:'Source Serif 4',serif;font-size:1.1rem;font-weight:600;color:#1c1917;">No conflict flags detected</p>
            <p style="color:#78716c;font-size:0.82rem;max-width:440px;margin:0 auto;line-height:1.6;">
                Flags are generated by cross-referencing campaign donations with bill sponsorship patterns.</p>
        </div>""", unsafe_allow_html=True)
    else:
        # Summary
        sev_counts = {}
        for f in conflicts:
            s = f.get("severity", "low")
            sev_counts[s] = sev_counts.get(s, 0) + 1

        c1, c2, c3 = st.columns(3)
        with c1: st.metric("Total Flags", len(conflicts))
        with c2: st.metric("Medium+", sev_counts.get("medium",0) + sev_counts.get("high",0))
        with c3: st.metric("Legislators", len(set(f.get("leg_name") for f in conflicts)))

        st.markdown("---")

        for f in conflicts:
            sc = {"high":"r","medium":"o","low":"m"}.get(f.get("severity",""),"m")
            pc = {"R":"#dc2626","D":"#2563eb"}.get(f.get("party",""),"#78716c")
            policy = (f.get("policy_area") or "").replace("_"," ")

            evidence = f.get("evidence")
            if isinstance(evidence, str):
                try: evidence = json.loads(evidence)
                except: evidence = {}

            donors_html = ""
            if evidence and evidence.get("top_donors"):
                donors_html = "<div style='margin-top:0.4rem;'>"
                for d in evidence["top_donors"][:3]:
                    donors_html += f"<span style='font-size:0.72rem;color:#78716c;'>{d['name'][:25]} · ${d['amount']:,.0f}</span><br>"
                donors_html += "</div>"

            st.markdown(f"""<div class="lc">
                <div style="display:flex;align-items:center;gap:0.4rem;margin-bottom:0.3rem;">
                    {t(f.get('severity','').upper(), sc)}
                    <span style="font-weight:500;color:#1c1917;font-size:0.88rem;">{f['bill_number']}</span>
                    <span style="color:#d6d3d1;">·</span>
                    <span style="color:{pc};font-weight:500;font-size:0.82rem;">{f.get('party','')}</span>
                    <span style="color:#57534e;font-size:0.82rem;">{f.get('leg_name','')}</span>
                    <span style="font-size:0.63rem;color:#a8a29e;margin-left:auto;">{policy}</span>
                </div>
                <p style="font-size:0.83rem;color:#44403c;line-height:1.6;margin:0;">{f['description']}</p>
                {donors_html}
            </div>""", unsafe_allow_html=True)

        # Export
        df = pd.DataFrame([{"bill": f["bill_number"], "legislator": f.get("leg_name",""),
            "party": f.get("party",""), "severity": f.get("severity",""),
            "description": f["description"]} for f in conflicts])
        st.download_button("Export CSV", df.to_csv(index=False), "lattice_conflict_flags.csv", "text/csv")

st.markdown("""
<div style="margin-top:1.5rem;padding:1rem;background:#fafaf9;border-radius:8px;border:1px solid #ebe9e7;">
    <p style="font-size:0.75rem;color:#78716c;line-height:1.7;margin:0;">
        Campaign contributions are legal. A statistical pattern between donations and legislation
        does not establish causation, quid pro quo, or corruption. These flags facilitate public
        scrutiny — they are not accusations. See <a href="/methodology" style="color:#4338ca;">methodology</a> for details.
    </p>
</div>
""", unsafe_allow_html=True)

st.markdown(footer(), unsafe_allow_html=True)
